# Generated by Django 5.1.5 on 2025-02-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklisting",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_images/"),
        ),
    ]
