# Generated by Django 5.1.5 on 2025-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklisting",
            name="descriptions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
