# Generated by Django 5.1.5 on 2025-02-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_booklisting_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
