# Generated by Django 5.1.5 on 2025-02-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_booklisting_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklisting",
            name="bought",
            field=models.BooleanField(default=False),
        ),
    ]
