# Generated by Django 5.1.5 on 2025-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_booklisting_bought"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="Not Provided"),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="Not Provided", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default="Not Provided", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(default="000000", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(default="Not Provided", max_length=100),
        ),
    ]
