# Generated by Django 5.1.5 on 2025-02-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_orderassignment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgraderequest",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready_to_ship", "Ready to Ship"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("issue_reported", "Issue Reported"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="upgraderequest",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("seller", "Seller"),
                    ("admin", "Admin"),
                    ("courier", "Courier"),
                    ("unassigned", "Unassigned"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("seller", "Seller"),
                    ("admin", "Admin"),
                    ("courier", "Courier"),
                    ("unassigned", "Unassigned"),
                ],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
