# Generated by Django 5.1.5 on 2025-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order_address_order_city_order_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("issue_reported", "Issue Reported"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
