# Generated by Django 5.1.5 on 2025-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_order_address_order_city_order_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklisting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
