# Generated by Django 5.1.5 on 2025-02-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_order_status"),
        ("core", "0005_orderassignment_status_orderassignment_updated_at"),
    ]

    operations = []
