# Generated by Django 5.1.5 on 2025-02-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20250208_2033"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderassignment",
            name="status",
        ),
    ]
