# Generated by Django 5.1.5 on 2025-02-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_orderassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_description", models.TextField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_issue",
                        to="core.orderassignment",
                    ),
                ),
            ],
        ),
    ]
